### PR TITLE
Medium-sized code improvements

### PR DESCRIPTION
**Pull request by 8bat**
Well, if you're OK with changes, here are some more :)

This PR makes user-visible changes, including some changes to existing behaviour that might need to be mentioned in release notes.  I've tried to explain my reasoning in the commit messages, but in general these should make ngPAWS behave more intuitively for players.

There are also a few wiki changes associated with this PR ([diff](https://github.com/8bat/ngPAWS/wiki/_compare/ddf573e0eec7f3e7d9eea7f5975e90aaa8eaac46...ab89490ba18ad9098381b3d0a349e5e40b307d3d), [log](https://github.com/8bat/ngPAWS/wiki/_history)).  I suspect it's easier to just ask you to pull them, but I'm happy to open an issue if you like.

FYI, my next group of commits reach deeper into the code, e.g. creating new hooks.  I hope to have another PR ready this weekend, but it might take a few days to get everything sorted out.

### CODE REVIEW

**Comment by 8bat** [comment]
A couple of points I didn't mention about the {EXITS} sequence tag:

1. I'm afraid I don't speak Spanish, so can only contribute English documentation.  This will be a bigger issue with future commits that need more documentation :s
2. The intended use case for the {EXITS} tag is to display a list of exits in the prompt.  I haven't really mentioned that because it might be controversial and because there are plenty of other use cases.  Happy to update docs or even put it in the start database if that's better

**Comment by Utodev** [comment]
Hi there,
Sorry for the late reply, I'm incredibly busy lately. To be honest, I'm so busy that I don't have time to check all over the commits in your pull requests, so I'm afraid I have to ask you for a detailed list of changes and reasoning, so I  can take decisions easier. 

I'm sorry to have to ask you for that , but I have had a look at these a couple of times since you requested the pull, but avaliable time doesn't allow me to check in depth.

About spanish documentation, don't worry about it, just drop me some notes about changes made and why, and I'll pull your changes and then make them in spanish too.

**Comment by Utodev** [comment]
Today I had more time to work on this, and I've found most of your commits are OK, but I had a problem accepting only some commits, and the only way I found to solve that is having a pull request made to another branch, not master, so then I can cherry-pick commits from master.

As I don't know when I would have time again to dedicate some time, I decided not to ask you to change destination branch, but making a self pull-request from your repository, what has been merged in a new branch named 8bat-branch.

Then I've picked all your commits from that branch and merged them into master, but three of them. I'll talk abou those below. 

In the end, this pull request has not been merged at all, but the other one I created, so I belive this one will have to be closed without merge. So if you are sending more changes in the future, including any changes made on the three commits I have put on hold, may you please always request pull on your branch instead of master? That helps a lot to merge some commits and not others.

Please close this pull request when you have opened another one.

Regarding the three commits I have not merged:

Rejected
========
Allow the player to drop worn objects - https://github.com/Utodev/ngPAWS/pull/29/commits/a0449428048d88d410b237b8453d7a83641b3300

Yes, I know is good to allow this, but it affects backwards compatibility and if you want your game to allow it you can allways change it in the response table. (adding something like this before the AUTOD call: DROP _ CARRIED @51 PLACE @51 @38 WRITE "You drop _." DONE). In general, this kind of things the author can fix, should not be modified at a lowe lever :-)

Needs amendment
===============
Ignore the weight of worn objects by default - https://github.com/Utodev/ngPAWS/pull/29/commits/00a3ec6814b404467ce2c79d595671e11566f09f

Well, I'm not sure if ngPAWS behaviour or PAWS one should be chosen,to be honest is a surprise for me that worn items are no counted in PAW. Anyway, if this change may affect existing games there should be a way the game author may change the setting without having to modify the javascript code. To do so, I belive the best option is handling that option in the 9th bit of the flag #12. As it defaults to 0, we will name that bit "worn_items_have_weight" bit, so by default they doesn't count, but author can change that by using BSET 12 9.

May you change the code so instead of worn_items_have_weight the code uses the current value of bit 9 (flag #12)?

I could change it myself of course, but if you do it you'll be credited in the commit list at least.

Need feedback
=============

Make {ACTION} show a useful status bubble  - https://github.com/Utodev/ngPAWS/pull/29/commits/2fe83d8d96f340695d2cf45501bb498fa68ffb8b

How does it work? May you send an screenshot or similar?

**Comment by Utodev** [comment]
I have also pulled your changes in documentation to my repository, and added myself EXITS sequence tag description to spanish version of docs.

Thanks for all your work!

**Comment by 8bat** [comment]
I've been busy too lately, so I've let this slip a bit.  Here's a quick reply now while you're about - I'll probably write something a bit more in-depth when I'm back up to speed.

Allow the player to drop worn objects - a044942
---

I vaguely remember having trouble making this work well as a response, but that might just be because I hadn't understood the "@&lt;flag&gt;" trick...

* I couldn't find documentation for @&lt;flag&gt; - is the rule that "any parameter of type 'value' can be passed @&lt;flagno&gt; instead"?  Or does it work for other types as well?  Happy to send a doc patch if that would help :)
* unless I dig up a half-forgotten edge case, it would be good to add your workaround to the start database (so it's easier for authors to add if they want).  I don't mind whose name goes on that commit, but if I do it would you prefer it was commented out by default?

Ignore the weight of worn objects by default - 00a3ec6
---

I'm fine with making this configurable by authors - in fact, configurability will be a big theme in some later patches.  In general, would it be fair to say that:

* we should be compatible with older versions of ngPAWS first, PAW second (so worn items *should* have weight by default)
* authors should be asked to enable PAW-compatibility one feature at a time (instead of something like a big "back compat" switch)
* patches that add PAW-compatibility should define new bit positions in flag 12 as needed
* there's no upper-bound to the number of bits in flag 12 - nothing limits it to a 8/32/128/X-bit number

Speaking of flag 12, I'm concerned that `BSET 12 9` isn't very readable.  How about if the next patch includes changes to the start database along the lines of:

```
#define flg option 12
#define const oWornItemsAreWeightless = 9

...

; PAW didn't count the weight of worn objects.  Uncomment the following line to enable compatibility with that bug:
;BSET option oWornItemsAreWeightless
```

Calling it a bug and disabling it by default seems like the quickest and cleanest way to explain the issue.  If that's OK, I'll add constants for the other bits in flag 12 as well.

Make {ACTION} show a useful status bubble - 2fe83d8
---

action-status-bubble

You can also see it live at https://8bat.github.io/vbca/play/

This is kind of a dumb trick, but it seems to work well enough.  Instead of creating a normal link like &lt;a href="https://github.com/"&gt; or &lt;a href="mailto:user@example.com"&gt;, this creates a link like &lt;a href="type: some text"&gt;.  Browsers assume "type" is a protocol name they've never heard of and display the text in the bottom-left of the screen.  This allows users to hover over a link and see where it would take them just like they would for a link to another page.

Last comments
---

Like I say, I'm a bit rusty on this, so I might come back with clarifications.  This message is just to get general answers while you've got some free time :)

**Comment by Utodev** [comment]
I'm quite surprised that I forgot to mention indirection in the documentation, but I actually did. I have just created a new chapter to describe it, cause it is very important and powerful:

https://github.com/Utodev/ngPAWS/wiki/Indirection

I'm afraid you'll have to pull my changes in the wiki :-)

I agree with the "backwards compatible with ngPAWS first" rule, so I agree with your change in the bit label/name.

I also think labeling the system flags may be useful, but we already have a convention for constant names, so system flag 12 should be named "fOptions" and not "option". About the specific bits in the options flag, "oWornItemsAreWeightless" woudl be ok, but it's confusing, as somewhere is also recommended to let object labels start withan 'o' (i.e. oLamp) so I'd rather go for "ofWornItemsAreWeightless" (options flag), or "sWornItemsAreWeightless" (setting). On the other hand, bits 49 and 53 are also updated bitwise, but they can also be considered settings, so there may be more flag contants and maybe is better fGeneralSettings=12, fInputSettings=49 and fObjectPrintFlags=53, and then each bit has its own constant with of or s prefix.

I like the idea of having some options already in the start database, but commented, so go ahead with that on the english database. I will do the same in the spanish one once I see which ones you added. In fact the spanish database already sets one flag on start, but in that case is not commented as it's a required one (basically tells the parser is a spanish game).

Finally, about the status bubble, I see your point, but again, some authors may not like it, some other will consider it appears in the precious graphic frame they managed to create, etc. So although I like the idea, my proposal is that you create that feature as a new plugin, to be added to the plugins folder, and documented in the whatsnew.txt file. Please if you do so, use the same license the ohter plugins do (MIT)

You have a sample quite similar to what you need to do here:

https://github.com/Utodev/ngPAWS/blob/master/plugins/condact_sequence_lib/condact_sequence_lib.jsp

And although I belive you already know hooks, maybe you have to have a look at the hooks page again.

**Comment by 8bat** [comment]
Ok, I'll make a new pull request (probably tomorrow) with fGeneralSettings=12, fInputSettings=49, fObjectPrintFlags=53, and sBlahBlah=value for the existing settings.  Then I'll make another PR that just handles object weight, as these issues have diverged a bit by now.

About dropping worn objects - I'm fairly convinced we need some kind of code solution, but I'm still sorting out my thoughts.  I'll write another message in this thread later tonight when I'm sure.

About the status bubble - this is the current behaviour:

current-action-status-bubble

Undoing that in a plugin will be complicated and will probably fail in some cases, so it would be better to handle this in `runtime.js`.  How about pulling the text from a system message?  Something like this:

```
/STX
...
/70 ; contents of the href attribute for {ACTION}s (shown in the bottom-left of the screen when the user hovers over them):
type: {AREF}
;http:// ; don't show anything
```

A quick test shows that `http://` works in Firefox, but I haven't tested in other browsers.  And `{AREF}` strikes me as a natural name for the action text, but I'd be happy with something else.

**Comment by 8bat** [comment]
I've now read back through the my database.  I'll test it properly tomorrow, but here are my thoughts so far about dropping objects.

Default rule in the start database
---

How about patching the start database something like this (changed slightly from above):

```
DROP _
 NOTEQ 51 255  ; Is there any referenced object in the player order? 
 WORN @51      ; Is it worn?
 AUTOR         ; Remove it so it can be dropped

DROP _        ; Generic
 AUTOD
 DONE
```

This should have the desired effect for the most common case, while still using the normal code as far as possible (standard system messages etc.).

Methods of dropping
---

I had to read the documentation several times to understand the difference between `DROP`, `DROPALL` and `DOALL 254`.  I'll probably submit a documentation PR at some point to make that clearer.

`DROP` as part of a separate response
---

I can't see a neat way to `DROP` a potentially-worn object as part of some other action, like:

```
RUN FASTER
 CHANCE 50
 WRITELN "In your haste you drop the MacGuffin."
 DROP oMacGuffin
 WRITELN "The monster is still gaining on you."
```

You'd need several rules to make this work (set a variable based on chance, unwear the MacGuffin if worn, then drop it if carried).  That's not too bad in the case above, but the complexity would soon add up in a real database, and anyway it feels a bit too much like programming.

How would you feel about a plugin command called something like `REMDROP` that calls `REMOVE` if worn, then `DROP` no matter what?  So authors don't have to care until they stumble over the problem, then they can add the plugin when the time comes.

Quill compatibility
---

I realise compatibility with The Quill isn't a goal of ngPAWS, but I'm converting a Quill game, so it's on my mind :)

The Quill's `DROP` command automatically removes items before wearing them.  As well as the benefits above, a `REMDROP` plugin would make it easier to port Quill games.

Alternative solutions
---

Here are some ideas I'm less fond of, but thought I'd mention for context:

* a `sRemoveBeforeDrop` setting - I suspect authors would find this a confusing workaround for an edge case, and it makes the common behaviour opaque for the sake of an edge case
* calling it `QDROP` or `QUILLDROP` instead of `REMDROP` - I'm happy to go with another name for the command, but the name should make sense without knowing the whole development history

**Comment by Utodev** [comment]
Hi,

I have finally merged the bubble thing commit, although I'd say your idea of adding the text as a system message is a good idea, specially considering that otherwise the text "type: " would appear in every game, even on spanish games. If you don't mind, make it use next free system message, and update both start databases (for spanish the proper text is "teclea: ".

Regarding the drop thing, the main problem is not being able to drop worn objects is not a bug, it's a feature,  so patching the start database doesn't look as a solution to me, cause to begin with I see no problem to solve. Said that, I understand that if worn objects could be dropped straight ahead, it may be more comfortable por players at some points, but I think wether to allow that or not it's a author's decision.

Your code using AUTOR would work fine unless the user has full inventory, in which case the "You cannot remove that,  your hands are full" message will appear. Wether that makes sense for you or not, in the end it's again an author decision. I have updated the example in the indirection manual page so instead of WRITE it calls SYSMESS 39, the system message for dropping. My solution is able to drop worn objects even with hands full. Both your and my solutions are ok, just depends on the login you want to apply. Same goes for the default behaviour, is not wrong, is just different.

About your example of drop in the middle of a response, the fact is you are not using the best approach. First, because if you want the McGuffin to fall in any case  you don't use DROP, you use PLACE, second cause in case of DROP succeeds in your solution you'd see something like "In your haste you drop the MacGuffin. You drop the McGuffin." I think the best approach for that case is:

`
RUN FASTER
 CHANCE 50
 WRITELN "In your haste you drop the MacGuffin."
 PLACE oMacGuffin @38
 WRITELN "The monster is still gaining on you."
`
Anyway, there are probably other situations where what you want to say when including a DROP inside a response may not be that easy to do, but in the end an Author will have to write code, and that's what writing the game is about.

This is the third PAW based game engine I've built, and I made a mistake in the first one I try not to repeat: it had more than 300 condacts, many options, and a very very long manual. Having too many condacts makes the documentation too long, too boring, and many people is unable to remember most of them, so with ngPAWS I've tried to keep it simple and don't add many new condacts unless what those condacts do is impossible to do with other condacts, and what you ask is clearly doable. 

Does that mean I don't like the idea of a REMDROP condact? No, I encourage you to create your REMDROP plugin condact, and make it public for other future authors, but please put it into the plugins folder, create a new one called remdrop_lib, and make it be a self-documented plugin. I'll add it to the whatsnew.txt file so people know it exists, but won't add it to the "official" list of condacts :-)

**Comment by Utodev** [comment]
By the way, I wonder if your native language is english. I tried to find people to check the english start database and their messages, but was unsuccessful, so the english start database is shorter and simpler than the spanish one, and I'm not 100% sure it's not returning some broken english sentences  :-(

**Comment by 8bat** [comment]
Happy to take a look at the English start database, but English is my *only* language, so if there are things missing I'll probably need help :)

Looking back through the thread, my plan for tomorrow is to put together a PR called something like "documentation and start DB improvements" with:

1. pretty names for setting flags/values in the DB
2. the word "settings" used in [the System-flags page](https://github.com/Utodev/ngPAWS/wiki/System-flags) in a way that's consistent with the new names in the DB
3. a review of the English DB, with comments about anything that seems not to have been copied from the Spanish DB
4. a general language pass for the English DB
5. (probably) some sort of documentation about manipulating objects (get, drop etc.)

That looks like at least a day's work, so I'll come back after that and re-evaluate the other work we've discussed in this thread.

About dropping - I think I'm looking at this from three (largely unrelated) angles:

1. compatibility between different engines.  When the same command means different things in different engines, that's going to cause confusion and the solutions are never going to be pretty.  `DROP` is actually the least awkward of these, and it's probably best to come back to it at the same time as the other things (like `BEEP`)
2. player agency.  I take the point that doing things behind the player's back takes away their control, but the only way to *give back* control is to have more active language in the messages.  I'll think about this more tomorrow when I'm writing properly, but how about if the default message was something like `You need to {ACTION|Remove {OREF}|remove {OREF}} first`?
3. learnability for authors.  I take the point that adding redundant condacts isn't a solution, but it's taken us all day to figure this one out and we're still not done (`PLACE oMacGuffin @38` places the item even if you're not carrying it - I think this would work if you added something like `PRESENT oMacGuffin` and `ISNOTAT oMacGuffin HERE`).  It seems like there's a micro-tutorial in all of this - using all the little examples to tell a story about building up complex rules from simple primitives.  Again, one to look at when I'm in documentation mode

**Comment by Utodev** [comment]
Fast thoughts about dropping, as today will be a busy familiy day for me:

1. Compatibility won't work, there is too much to do to make ngPAWS PAW compatible, an though it looks very similar, it actually differs in many options, being the issue with BEEP the lesser one. ngPAWS was not created to run PAW games, but to have a similar programming language to PAW. Trying to get full compatibility with PAW will require lots of changes and then lots of settings, so much I don't like the idea, the complexer the code is, the longer the manual will become. Honestly, if you plan to make ngPAWS 100% PAW compatible, I'd suggest you to fork the solution completely and start modifying it 100% free of restrictions (and name it something esle like PAW.js or similar)

2. I like your solution, but be careful with messaging as many system messages are used in more than one action, maybe this one is one of them and though that message looks good for the case we are talking about, won't be that good for other cases.

3. You're right, the code would need either two entries or using sharp condacts, though the CHANCE condition aldeady forces that situation:

```
RUN FASTER
 CHANCE# 50
 {
   WORN# oMacGuffin
   {
   WRITELN "In your haste you drop the MacGuffin."
   PLACE oMacGuffin @38
   }
 }
 WRITELN "The monster is still gaining on you."
...
```

When adding sharp sign to a condition, it only affects next instruction/block so if chance 50 succeeds then if WORN oMacGuffin succeeds, then WRITELN and PLACE will be run, otherwise only whatever is after the second closing curly bracer will be executed.

3. Maybe a litlle tutorial helps, yes. In fact I've seen I have a whole section of "micro-tutorials" that is empty in the english version of the documentation (but it's plenty of them in the spanish version). It seems I have to tranlate those tutorials but I had absolutely forgotten I had that task pending. I'll have a look at them in the following days and see if I can start translating them and get that task done in a pair of weeks.

**Comment by cibersheep** [comment]
I'm excited to see your work. If I can help with that language bridge, I'll be happy to be helpful. You can ping me on Telegram http://t.me/cibersheep if you need help with the texts

**Comment by Utodev** [comment]
Long time ago I prepared a test game to test english library for a guy that was about to help me, but in the end he vanished. Maybe is good that you check spelling, grammar, etc, on this game, although start database may have been updated since then:

https://www.dropbox.com/s/mew0ycbbcbgmjbb/test_English03.zip?dl=0

**Comment by 8bat** [comment]
@Utodev - you read my mind!  That should be useful for testing changes.  I've spent today looking through the differences between the English and Spanish databases, and am still less than halfway through.  At this point, I expect to send you a PR in a day or two that just synchronises the existing databases as far as I'm able.  Improving messages etc. will have to wait.

@cibersheep - if you don't mind some boring work, I would be very grateful for the help when the next PR's done.  I'm pretty good at *finding* differences between databases, but without knowing the language I can't even start work on translation.  For example, in English "PUT NOUN IN CONTAINER" means something different to "PUT NOUN DOWN", so there's a special rule in the English DB to handle that ambiguity.  That might be missing from the Spanish DB because the phrase isn't ambiguous in Spanish, but otherwise it'll need translating somehow.  (this is just one of many examples)

**Comment by 8bat** [comment]
A few questions to do with the start database:

1. some of the values for flag 12 are set by the author at the start of the game (like the game language), others are set by the engine throughout the game (like whether an unknown word was found after the verb in the latest command).  Is it better to give these all the same prefix (sName), or should there be a different one for each type?
2. strings like `&&_voc_EXTRACT` occur in a few places.  This seems to be a way of indirecting into the vocabulary table - should it go in the indirection chapter (which, by the way, thanks for)?
3. what is a pronominal suffix?  Can it be safely ignored in English?
4. I may well have misunderstood, but [database.start.spanish line 970](https://github.com/Utodev/ngPAWS/blob/master/installation_aux_files/database.start.spanish#L970) seems to insert an item when the user tries to wear it - is that correct behaviour?
5. some words have different numbers in each language (e.g. "suicide" is verb 99 in English, but 81 in Spanish).  What do you think about renumbering English words to match the Spanish where possible?

@cibersheep - whether or not we renumber English words, it would be a big help if I had a definitive list of words that mean the same thing in each language.  If I made a list of Spanish words and my best guess at the English equivalent, could you rearrange them to actually match up?  I can do it in whatever format you like, e.g. an Excel spreadsheet or a table in a wiki.

**Comment by Utodev** [comment]
Here I go:

1. Hmmm... yes, not all the bits in the settings flags are actually settings, maybe fSettings is not the best name for the flag itself, nor s the proper prefix for them all, but I can't think a good name for it. Does "subflag" makes any sense for you? If so, maybe calling the flag fSubFlags and each bit sfWhatever may be the solution.

2.  It's not indirection, it just happens the preprocessor generates const for each vocabulary word automatically, that is, there are tons of implicit lines like this:

`#define const _voc_XXXX nnn`

Then, the preprocessor has a long stroy behind, and initially it was required to precede every constant use by the double & sign, that is, you cannot write GET oKEY, you had to write GET &&oKEY. At some point it was improved and it was accepting two or just one &, and finally it's not even required, but for backwards compatibility all &&oKey &oKey and oKey are supported. 

What you see is a combination of both features, that hasn't been corrected as it's working, although the && signs could be removed.

It has nothing to do with indirection, for indirection the @ character is used, as a way to make @fMyFlag mean what is **at** flag fMyFlag.

3. In spanish the equivalence to DROP IT isDEJALO, where DEJA is the verb and LO is a pronominal suffix equivalent to english IT. THere are several pronominal sufixes that replace enlish IT and THEM. I belive you can safely ignore them in english, except for making sure it's disabled in english database, or otherwise a word like EXIT maybe interpreted as "EX IT" and therefore EXAMINE last referenced object.

4. In spanish PONER means basically PUT, but when talking about clothes means WEAR, on the other hand PONER EN means PUT INTO (put whatever into the chest) and PONER SOBRE means PUT ON (put whatever on the table).

5. It's ok for me. I don't think any word is referenced by number, but by identifier _voc_XXXX, but you'll need to make sure there are no entries that change flags 33-37 or 43-47 using the number instead of the constant. I don't think there's any of those, but I'm not 100% sure. If flags are changed using _voc_XXX and all the SYNONYM also reference words by the _voc_XXXX label, then it'll be OK.

**Comment by 8bat** [comment]
I'm starting to make a list of start database changes to think about when I'm a bit more confident (e.g. once I've had a go with that test game).  I'll put "remove &&s" and "renumber words" on the list, and we can talk about them when the time comes.  In the mean time, I'll add a comment explaining pronominal suffixes and work on the English "PUT" logic.  I hadn't thought about it before, but "PUT COAT ON" means "WEAR COAT", whereas "PUT COAT ON HOOK" means "INSERT COAT".

I'm in two minds about the word "subflags".  It's a fine word for authors that know nothing or everything about programming, but boolean variables are sometimes explained to newbies by analogy with raising and lowering flags, and occasionally even called "flag variables".  Normally that edge case wouldn't be big enough to worry about, but I suspect the people who write adventure game are likely to also dabble in programming just enough to think a sub-flag was somehow half a boolean variable.  Since the main difference to authors is that they *set* some settings and *check* others, how about "ss" and "cs" prefixes?  So e.g. `BSET fGeneralSettings ssSupportPronominalSuffixes` and `BZERO fGeneralSettings csUnknownWordFoundAfterVerb`?

**Comment by cibersheep** [comment]
@8bat "renumber words": Yep, I can do that reordering. I use LibreOffice, so any kind of spread sheet is fine with me.

**Comment by 8bat** [comment]
@cibersheep - great!  I've created issue #30 to keep track of renumbering.  I mentioned you in the message, so I assume you got an e-mail.  Otherwise, please subscribe.

By the way, it turns out github supports `.xslx` spreadsheets but not `.ods`.  The file opens fine in LibreOffice for me, but let me know if you have any problems.

**Comment by Utodev** [comment]
This was already merged (partially)

**Pull request closed without merging**
