### PR TITLE
Initial Catalan Support

### PR DESCRIPTION
**Pull request by cibersheep**

### CODE REVIEW

**Comment by Utodev** [comment]
This is an awesome work! Really impressive, and yes, sometimes you require a few tricks, but it's OK when there's no other (easy) way. 

I'd be pulling this pulls request now, but I'm afraid it's included the updated "help.jsp" with angular quotes I rejected in the other pull request, so we have two options:

1) You wait until I have the time to see how to partially pull this pyll request, something I know can be done but I can't recall how.

2) You make another pull request without that commit.

**Comment by cibersheep** [comment]
Thanks for your kind words ^__^
I'm planning to create a translation of a game I just finished and I'm sure I will find some errors :) (a fun way of debugging).
Sorry for the help.jsp in there (I branched my version and not yours).
Let me reverted in my branch. That will keep your original help file again... sorry

**Comment by cibersheep** [comment]
Ouh. Nice. I have reverted the angular quotes in help.jsp but fixed the typos.
So, if you like it, you could merge that. If you want me to change something else, tell me :)

**Comment by Utodev** [comment]
Merged! Thanks!

**Pull request merged**
