### PR TITLE
Update path to ngpc

### LINKED ISSUE #62: Build: Path to ngpc changes in Ubuntu 22.04
Ubuntu 22.04, Lazarus 2.2.0, during build, `ngpc` is located in a different location.

https://github.com/Utodev/ngPAWS/blob/0a380e282eef6b4ad062868a788887522ef52394/build_linux.sh#L60

Line 60 needs to be replaced with

```bash
mv build/compiler/VisualStudio/.vs/ngpc dist/ngpc
```

After the change, `build_linux.sh` successfully compiles ngPAWS.

### PR DESCRIPTION
**Pull request by mmartinortiz**
The path to `ngpc` is different when compiling using Ubuntu 22.04 and Lazarus 2.2.0.

This patch provides the new path to `ngpc`

Closes #62

### CODE REVIEW

**Comment by cibersheep** [comment]
This might not be the right way of fixing the issue.
Can't you get the compiled route after in a variable? Otherwise the script will fail for users that doesn't use VisualStudio

**Comment by cibersheep** [comment]
> I can make the new path part of a variable,

Thanks, that would make it work in future (and past) systems then

> but I do not use VisualStudio, I assumed that during build, some library had used the VisualStudio SDK. 

That is interesting as I build it (on 20.04) and the resultant path is the one I added to the .sh

**Comment by mmartinortiz** [comment]
I've resolved the conflicts with current master and replaced the path to `ngpc` with a function that search for the most recent `ngpc` folder (the one just compiled)

**Comment by cibersheep** [comment]
Oh! That's really, really AWESOME!
Thank you

**Pull request merged**
